[project]
name = "mp-events-hub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiobotocore>=3.0.0",
    "aiosmtplib>=5.0.0",
    "alembic[async]>=1.17.2",
    "asyncpg>=0.30.0",
    "bcrypt>=5.0.0",
    "dishka>=1.7.2",
    "elasticsearch>=8.13,<9.0",
    "fastapi>=0.121.2",
    "faststream[rabbit]>=0.6.3",
    "greenlet>=3.2.4",
    "httpx>=0.28.1",
    "mypy>=1.19.0",
    "pika>=1.3.2",
    "pillow>=12.0.0",
    "pre-commit>=4.3.0",
    "pydantic-settings>=2.12.0",
    "pydantic[email]>=2.12.4",
    "pyjwt>=2.10.1",
    "pytest-asyncio>=1.3.0",
    "python-multipart>=0.0.20",
    "redis>=7.1.0",
    "ruff>=0.14.8",
    "sqlalchemy>=2.0.44",
    "uuid-utils>=0.11.1",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "asgi-lifespan>=2.1.0",
    "pytest>=9.0.1",
    "testcontainers>=4.13.3",
]
